✨ working gre_field_unwarp. register_func2struct: transform_dir

diff --git a/gre_field_unwarp b/gre_field_unwarp
--- a/gre_field_unwarp
+++ b/gre_field_unwarp
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+set -eo pipefail
+trap 'e=$?; [ $e -ne 0 ] && echo "$0 exited in error"' EXIT
 
 #
 #  quickly test out gre fieldmap configurations
@@ -7,45 +9,60 @@
 #  20201228WF  init
 
 scriptDir="$(dirname $0)"
-export logFile="" # no logging
 source "${scriptDir}/preproc_functions/helper_functions"
 source "${scriptDir}/preproc_functions/prepare_fieldmap"
 source "${scriptDir}/preproc_functions/prepare_gre_fieldmap"
-set -eo pipefail
-trap 'e=$?; [ $e -ne 0 ] && echo "$0 exited in error"' EXIT
+source "${scriptDir}/preproc_functions/register_func2struct"
+source "${scriptDir}/preproc_functions/prepare_mc_target"
+source "${scriptDir}/preproc_functions/fast_wmseg"
 
 # FM_ - fieldmap space
 # EF_ - epi space 
-# MP_ - t1 mprage space
 #
 # _D   - distorted (origianl)
 # _UD  - undistored (corrected)
 
 fm_cfg=; epi=; mag=; phase=;
 # initialize vars allowed to be none
-func_to_struct=""
+fmap_struct_dof=bbr
 mprage_bet=""
 savedir=""
 
+usage(){
+   # usage extracted from source
+   # match -OPT) .... # DESCRIPTON
+   # and spit out for documentation
+   echo -e "$(basename $0) USAGE: "
+   perl -lne '
+    BEGIN{$_=<> until /^\s*#DOCSTART/}
+    exit if /^\s*#DOCSTOP/;
+    print "  $1\t$3" if /(-.*?)(\)|\|).*?#(.*)/' $0|
+       column -ts$'\t'
+    exit
+}
+
 while [ $# -gt 0 ]; do
+   #DOCSTART -- options parsed by perl oneliner in usage()
    case "$1" in
-      -cfg) fm_cfg="$2"; shift 2;;
-      -epi) epi="$2"; shift 2;;
-      -mag) mag="$2"; shift 2;;
-      -phase) phase="$2"; shift 2;;
-      # optional
-      -mprage_bet) mprage_bet="$2"; shift 2;;
-      -func_to_struct) func_to_struct="$2"; shift 2;;
-      -savedir) savedir="$2"; shift 2;;
-      *) echo "unknown option '$1'!"; exit 1;;
+      -help|-usage|-h) usage;; # usage
+      -cfg) fm_cfg="$2"; shift 2;; # fieldmap configuration file (includes TEdiff, unwarpdir, ..)
+      -epi) epi="$2"; shift 2;;    # epi to undistort (one volume, e.g. mc_target.nii.gz)
+      -mag) mag="$2"; shift 2;;    # magnitude nifti (e.g. fmap/magintude1.nii.gz)
+      -phase) phase="$2"; shift 2;; # phase nifti (e.g. fmap/phase.nii.gz)
+      -mprage_bet) mprage_bet="$2"; shift 2;; # optional: structural to use for warping. (longer to run)
+      -quick) mprage_bet=""; shift;; # optional: remove mprage_bet if specified earlier. order dependent.
+      -savedir) savedir="$2"; shift 2;; # optional: folder to save everything (otherwise us fm_cfg name)
+      -nobbr) fmap_struct_dof=6; shift ;; #optional: disable bbr. use 6 dof warp instead
+      *) echo "unknown option '$1', see -help!"; exit 1;;
    esac
+   #DOCSTOP
 done
 
 [ -z "$fm_cfg" ] && echo "must have -cfg" && exit 1
 [ -z "$savedir" ] && savedir=fmcfg-$(basename $fm_cfg)
 
 # check paths and make absolute
-for var in epi mag phase mprage_bet func_to_struct fm_cfg; do
+for var in epi mag phase mprage_bet fm_cfg; do
    [ -z "${!var}" ] && continue
    [ ! -s "${!var}" ] && echo "$var '${!var}' does not exist or is zero size!" && exit 1
    printf -v "$var" "$(realpath ${!var})"
@@ -53,50 +70,74 @@ done
 
 source $fm_cfg
 [ -z "$dwelltime" ] && echo "'$fm_cfg' is missing 'dwelltime'" && exit 1
-[ ! -d $savedir ] && mkdir $savedir
 
-# Note from 2014-04: X direction bug!
-case $unwarpdir in
-   x-) fugue_unwarpdir=x;;
-   x) fugue_unwarpdir=x-;;
-   *) fugue_unwarpdir=$unwarpdir;;
-esac
+[ ! -d $savedir ] && mkdir $savedir
 
 cd $savedir
 savedir=$(pwd)
+
+# globals from preprocessFunctional
+logFile="$savedir/main.log" # no logging
+funcdir="$savedir"
+qa_imgdir="$savedir/qa"; test -d $qa_imgdir || mkdir $_
+qa_imglog="$savedir/qa/img.log"
+#fm_phasedir=$(pwd) DISTORTION_DIR=""
+bbrCapable=1
+use_ants=1
+ext=.nii.gz
+use_fm=1
+export FIELDMAP_TRANSFORMS_DIR="$savedir/transforms"
+test ! -d $FIELDMAP_TRANSFORMS_DIR && mkdir  $_
+
+
 3dcopy $phase phase.nii.gz -overwrite
 3dcopy $mag   mag.nii.gz -overwrite
-3dcopy "$epi" EF_D_mc_target.nii.gz -overwrite
+3dcopy "$epi" mc_target.nii.gz -overwrite
+test -n "$mprage_bet" -a ! -r mprage_bet.nii.gz && ln -s "$mprage_bet" $_
+# done by prepare_fieldmap (not preproc_fieldmap) 
 
+if [ -z "$mprage_bet" ]; then
+   echo "Run without warp to structural"
+   test ! -r mc_target_brain_restore.nii.gz && 3dcopy mc_target.nii.gz $_
+   3dcopy mc_target.nii.gz EF_D_mc_target.nii.gz -overwrite
+   prepare_gre_fieldmap mag.nii.gz phase.nii.gz
+   cd $savedir
+   ! test -r FM_UD_fmap.nii.gz  && ln -s unwarp/$_ ./
+   preproc_fieldmap
+   echo "INSPECT OUTPUT: "
+   echo "  afni" $savedir/EF_*D_mc_target.nii.gz
+   echo " and/or "
+   echo "  feh $savedir/qa/undistort_mc_target.png"
+   exit 
+fi
 
 
 ## deal with fieldmap files
 # create FM* files: FM_UD_fmap FM_UD_fmap_mag
-#fm_phasedir=$(pwd)
-prepare_gre_fieldmap mag.nii.gz phase.nii.gz
+DISTORTION_DIR=$savedir/fm_unwarp
+preprocessDistortion -phase $phase -mag $mag -fm_cfg $fm_cfg -savedir $DISTORTION_DIR -method gre.nii.gz
+DISTORTION_DIR=$DISTORTION_DIR/unwarp
+
 cd $savedir
+! test -r  EF_D_mc_target.nii.gz && 3dcopy mc_target.nii.gz  $_
 
 # create sigloss, mask, and warps
-export FIELDMAP_TRANSFORMS_DIR="./"
-qa_imgdir="$savedir"
-qa_imglog="$savedir/img.log"
-fmap_struct_dof=12 # not bbr
-fm_phasedir=phase.nii.gz
+#[ ! -r EF_UD_mc_target.nii.gz ] && preproc_fieldmap
+#preproc_fieldmap
+func_struct_dof=$fmap_struct_dof
 mprageBet="$mprage_bet"
-preproc_fieldmap
+prepare_mc_target
+prepare_fieldmap 
+cd $savedir # might not return to the correct directory
+register_func2struct
 
-# needs TEdiff 
-# saves --savefmap=${fm_phasedir}/FM_UD_fmap
-# fieldmap_make_rads_per_sec $fm_phase $fm_phasedir $fm_magnitude
-echo -e "# see\n\t afni  EF_{U,}D_mc_target"
-cd $savedir
-## warp to structural
-[ -z "$mprage_bet" ] && exit 0
-if [ -z "$func_to_struct" ]; then
-   func_to_struct=func_to_struct.mat
-   flirt -in EF_D_mc_target -ref $mprage_bet -out func_to_struct_init -omat $func_to_struct -dof 6 -interp spline
-fi
+# no bbr version
+set -x
+func_to_t1=""
+test -r unwarp/T1_UD_warp.nii.gz && func_to_t1=$_ # TODO: untested. what is non-bbr output name?
+test -r unwarp/T1_UD_warp_bbr.nii.gz && func_to_t1=$_
+[ -z "$func_to_t1" ] && echo "ERROR: cannot find unwarp/T1_UD*" && exit 1
+applywarp --in=mc_target.nii.gz --out=EF_UD_anat.nii.gz --interp=spline --ref=mprage_bet.nii.gz --warp=$func_to_t1
+ln -s EF_UD_anat.nii.gz "$(basename "$(dirname "$savedir")")_func_in_anat.nii.gz"
 
-convertwarp --ref=$mprage_bet --warp1=EF_UD_warp --postmat=$func_to_struct --relout --out=func_to_t1
-applywarp --ref=$mprage_bet --in=EF_D_mc_target --out=MP_UD_mc_target  --warp=func_to_t1
-echo -e "# compare other pipes against $(pwd)/MP_UD_mc_target"
+
