🐛 env|DEBUG typo; allow mag or mag1;dont require ses in pattern match

diff --git a/lncdprep b/lncdprep
--- a/lncdprep
+++ b/lncdprep
@@ -81,7 +81,7 @@ C<DRYRUN> - if set, will echo instead of running
 
 =cut
 env|grep -q ^DRYRUN=. && DRYRUN=echo || DRYRUN=""
-env|grep -q ^DEGUB=. || DEBUG=""
+env|grep -q ^DEBUG=. || DEBUG=""
 debug() { [ -n "$DEBUG" ] && echo "$@" || :; }
 
 
@@ -235,8 +235,9 @@ func() {
 }
 
 find_func(){
+   debug "# searching $BIDSROOT at depth $1 for dir 'func'" >&2
    find -L $BIDSROOT -maxdepth "$1" -type d -name func |
-      perl -lne 'print $1 if m:sub-([^/]*(/ses-[^/]*)):' |
+      perl -lne 'print $1 if m:sub-([^/]*(/ses-[^/]*)?):' |
       $CAT
 }
 
@@ -258,14 +259,26 @@ partial_ok(){
         return 1
      return 0
 }
+find_fm() {
+  # find fieldmap files (mag or phase)
+  local id="$1"; shift
+  local mag_or_phase="$1"; shift;
+  case "$mag_or_phase" in 
+   mag) mag_or_phase=".*magnitude1?.nii.gz";;
+   phase) mag_or_phase=".*phase.nii.gz";;
+  esac
+  local file="$(find -L "$BIDSROOT/sub-$id/fmap/" -name "$FMPATT" -regex "$mag_or_phase"| sed -n '$p')"
+  [ -z "$file" ] &&
+	  echo "MISSING FMAP: '$BIDSROOT/sub-$id/fmap/$mag_or_phase' (also $FMPATT)" >&2 &&
+	  return 1
+  echo $file
+}
 
 _lncdprep(){
   local id="$1"; shift
   if [ -n "$FMCFG" ]; then
      distortion_dir=$OUTDIR/FM/$id
-     fieldmap $distortion_dir \
-        $(find -L $BIDSROOT/sub-$id/fmap/ -name "$FMPATT" -name "*magnitude1.nii.gz"| sed -n '$p') \
-        $(find -L $BIDSROOT/sub-$id/fmap/ -name "$FMPATT" -name "*phase.nii.gz"| sed -n '$p')
+     $DRYRUN fieldmap $distortion_dir $(find_fm $id mag) $(find_fm $id phase)
      ARGS="$ARGS -distortion_dir $distortion_dir/unwarp"
   fi
 
