add NoisySkullstrip and 1mm t1

diff --git a/preprocessMprage b/preprocessMprage
--- a/preprocessMprage
+++ b/preprocessMprage
@@ -185,7 +185,7 @@ case "$reference" in
     MNI_1mm) bettedRefBrain=${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain;
 	unbettedRefBrain=${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c;
 	refMask=${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_mask_dil; #Jul2017: 3dmask_tool dil of brian mask
-	fnirtConfig=${stddir}/fnirtMNI1mm.cnf;;
+	fnirtConfig=${stddir}/fnirtMNI1mm.cnf;; # DONT TRUST THIS FILE # TODO: check/fix
     MNI_2mm) bettedRefBrain=${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain_2mm;
 	unbettedRefBrain=${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_2mm;
 	refMask=${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_mask_2mm_dil; #Nov2016: this is now a 1x dil, matching fsl_anat
@@ -480,9 +480,15 @@ elif [ -n "${brainmask}" ]; then
     fi
     rel "fslmaths ${T1}_biascorr -mas $brainmask ${T1}_bet_initial" #apply custom brainmask
     ssmethod=custom #override ssmethod so that fnirt-inv doesn't fire below
+
+# say we provide a already skullstripped image
+# optionally with the file name provided by -b (betOpts) otherwise named ${T1}_bet_initial.nii.gz
+elif [ $ssmethod = provided ]; then
+    [ -n "$betOpts" -a -r "$betOpts" ] && 3dcopy $betOpts ${T1}_bet_initial${ext}
+    [ ! -r ${T1}_bet_initial${ext} ] && echo "using $ssmethod, cannot find ${T1}_bet_initial${ext}" >&2 && exit 1
 elif [ $ssmethod = noisy ]; then
-   rel "@NoisySkullStrip -input ${T1}_biascorr${ext}"
-   rel "3dcopy ${T1}_biascorr${ext}.ns+orig. ${T1}_bet_initial${ext}" #default option for initial strip
+    rel "@NoisySkullStrip -input ${T1}_biascorr${ext}"
+    rel "3dcopy ${T1}_biascorr${ext}.ns+orig. ${T1}_bet_initial${ext}" #default option for initial strip
 else
     [ -z "$betOpts" ] && betOpts="-touchup -orig_vol" #default 3dss options
     rel "3dSkullStrip -input ${T1}_biascorr${ext} -prefix ${T1}_bet_initial${ext} ${betOpts}" #default option for initial strip
@@ -708,3 +714,5 @@ rel "Nonlinear warp of template brain onto subject (inverse warp). Check especia
 rel "   fslview ${T1}_bet${ext} template_to_subject_brain${ext}" c
 rel "Nonlinear warp of subject brain onto template. Look for alignment of sulci, especially along midline." c
 rel "   fslview $tbrain $( remove_ext ${outputFile} )_bet${ext}" c
+
+# vim: set tabstop=7:
