Fixed problem with mis-detection of -func_refimg being DICOM versus NIfTI

diff --git a/preproc_functions/check_requirements b/preproc_functions/check_requirements
--- a/preproc_functions/check_requirements
+++ b/preproc_functions/check_requirements
@@ -50,8 +50,8 @@ function check_requirements {
 	fi
 
 	#if funcRegImg is a single DICOM file, change to NIfTI
-	fslhd "$funcRefImg" 2>&1 | grep -q ERROR
-	if [ $? -eq 0 ]; then
+	dicom_hdr "$funcRefImg" 2>&1 | grep -q "ERROR: can't open.*as a DICOM file" #A 0 exit status from grep indicates a match
+	if [ $? -ne 0 ]; then
 	    rel "Converting -func_refimg to NIfTI" c
 	    rel "to3d -prefix epiref.nii.gz -ushort2float \"$funcRefimg\""
 	else
