explictely specify cleanup and keep_motion_files; fix missing files; comments

diff --git a/preproc_functions/helper_functions b/preproc_functions/helper_functions
--- a/preproc_functions/helper_functions
+++ b/preproc_functions/helper_functions
@@ -124,7 +124,10 @@ function cleanup_preprocessFunctional {
 	upre=""
     fi
 
+    [ -z "$funcFile" ] && echo "ERROR: $FUNC_NAME does not have funcfile!" && exit 1
+    #echo "func: $funcFile"
     #echo "dspre: $dspre"
+    #echo "wpre: $wpre"
     #echo "upre: $upre"
     #echo "smoothing_suffix: $smoothing_suffix"
     #echo "ext: $ext"
@@ -132,8 +135,8 @@ function cleanup_preprocessFunctional {
     #interleaved stream
     deleteFile t_${funcFile}${ext}
     #deleteFile mt_${funcFile}${ext}
-    deleteFile ${upre}mt_${funcFile}${ext}
-    deleteFile ${upre}mt_${funcFile}_mean_reg${ext}
+    #deleteFile ${upre}mt_${funcFile}${ext}
+    #deleteFile ${upre}mt_${funcFile}_mean_reg${ext}
     deleteFile k${upre}mt_${funcFile}${ext}
     deleteFile k${upre}mt_tmean_mask${ext}
     deleteFile ${wpre}${dspre}k${upre}mt_${funcFile}${ext}
@@ -143,7 +146,7 @@ function cleanup_preprocessFunctional {
 
     deleteFile k${upre}mt_${funcFile}_Tmin${ext}
     deleteFile k${upre}mt_${funcFile}_Tmin_10pctThr${ext}
-    deleteFile ${upre}mt_tmean${ext}
+    #deleteFile ${upre}mt_tmean${ext}
     deleteFile ${dspre}k${upre}mt_tmean${ext}
     deleteFile ${wpre}${dspre}k${upre}mt_${funcFile}_tmean${ext}
     deleteFile fs${wpre}${dspre}kmt_mean_float${ext}
@@ -174,10 +177,10 @@ function cleanup_preprocessFunctional {
     deleteFile s${wpre}${upre}${dspre}kmt_${funcFile}${smoothing_suffix}_usan_size${ext}
 
     #sequential stream
-    deleteFile m_${funcFile}${ext}
-    deleteFile m_${funcFile}_mean_reg${ext}
-    deleteFile ${upre}m_${funcFile}${ext}
-    deleteFile t${upre}m_${funcFile}${ext}
+    #deleteFile m_${funcFile}${ext}
+    #deleteFile m_${funcFile}_mean_reg${ext}
+    #deleteFile ${upre}m_${funcFile}${ext}
+    #deleteFile t${upre}m_${funcFile}${ext}
     #deleteFile tm_${funcFile}_tmean${ext}
     deleteFile ${dspre}kt${upre}m_${funcFile}${ext}
     deleteFile ${dspre}kt${upre}m_tmean_mask${ext}
@@ -287,9 +290,28 @@ function cleanup_preprocessFunctional {
     fi
 
 
+    ## Files left over from Finn's pipeline
+    #wktm_rest_1_98_2_mask_dil1x.nii.gz
+    #wktm_rest_1_98_2_mask_dil1x_templateTrim.nii.gz
+    deleteFile ${wpre}k${upre}tm_${funcFile}_98_2_mask_dil1x${ext}
+    deleteFile ${wpre}k${upre}tm_${funcFile}_98_2_mask_dil1x_templateTrim${ext}
+    ###
+
+    if [ -n "$upre" ]; then
+       deleteFile ${upre}mt_${funcFile}${ext}
+       deleteFile ${upre}mt_${funcFile}_mean_reg${ext}
+       deleteFile ${upre}mt_tmean${ext}
+       deleteFile ${upre}m_${funcFile}${ext}
+       deleteFile t${upre}m_${funcFile}${ext}
+    fi
+
     # remove motion files if we aren't told to keep them
     # this option implemented to keep time consuming 4d motion computation
     if [[ -z "$KEEP_MOTION_FILES" ]]; then
+
+      deleteFile m_${funcFile}${ext}
+      deleteFile m_${funcFile}_mean_reg${ext}
+
       deleteFile tm_tmean${ext}
       deleteFile tm_${funcFile}_tmean${ext}
       deleteFile tm_${funcFile}${ext}
@@ -303,5 +325,15 @@ function cleanup_preprocessFunctional {
 
       deleteFile mc_initial${ext} #initial motion correction to mean functional
       deleteFile mc_target_mask${ext} #brain mask for mc_target used for rmsdiff in motion_plots
+
+      # in case we missed the empty upre
+      deleteFile ${upre}mt_${funcFile}${ext}
+      deleteFile ${upre}mt_${funcFile}_mean_reg${ext}
+      deleteFile ${upre}mt_tmean${ext}
+      deleteFile ${upre}m_${funcFile}${ext}
+      deleteFile t${upre}m_${funcFile}${ext}
+
     fi
 }
+
+# vim: set tabstop=7:
diff --git a/preproc_functions/parse_args b/preproc_functions/parse_args
--- a/preproc_functions/parse_args
+++ b/preproc_functions/parse_args
@@ -1,5 +1,22 @@
 #!/bin/bash
 
+# read_preproc_cmd does not work!
+# sets $@ for function instead of global
+function read_preproc_cmd {
+ if [ -f .preproc_cmd ]; then
+   read cmd < .preproc_cmd
+   # disable wildcard expansion so that -dicom patterns don't get expanded
+   set -f 
+   # change positional parameters to stored settings
+   set -- $cmd
+   # re-enable wildcard expansion as usual
+   set +f 
+ else
+   echo "no .preproc_cmd files, cannot read!"
+   exit 1
+ fi
+}
+
 function rm_completefiles {
     rel "\nStarting over...\n\nRe-running all preprocessing steps\n" c
     deleteFile ".functional"
@@ -135,9 +152,12 @@ function parse_args {
 	    echo ""
 
 	    if [ $resume = y ]; then
-		set -f #disable wildcard expansion so that -dicom patterns don't get expanded
-		set -- $cmd #change positional parameters to stored settings
-		set +f #re-enable wildcard expansion as usual
+              #disable wildcard expansion so that -dicom patterns don't get expanded
+		set -f 
+              # change positional parameters to stored settings
+		set -- $cmd
+              # re-enable wildcard expansion as usual
+		set +f
 	    else
 		echo -e "\n\nQuitting script."
 		exit 0
@@ -165,16 +185,43 @@ function parse_args {
 	if [ -f .preproc_cmd ]; then
 	    read cmd < .preproc_cmd
 	    cmd="${cmd/-startover/}"
-	    set -f #disable wildcard expansion so that -dicom patterns don't get expanded
-	    set -- $cmd #change positional parameters to stored settings
-	    set +f #re-enable wildcard expansion as usual
+           # disable wildcard expansion so that -dicom patterns don't get expanded
+           set -f 
+           # change positional parameters to stored settings
+	    set -- $cmd
+           # re-enable wildcard expansion as usual
+	    set +f 
 	else
 	    echo "-cleanup_only or -startover specified alone, but no known preprocessing call in .preproc_cmd."
 	    exit 1
 	fi
+
+    elif [ $# -eq 2 ] && 
+         [[ "$@" =~ -cleanup ]] && # cleanup or cleanup_only, doesn't matter
+         [[ "$@" =~ -keep_motion_files ]]; then
+	cleanup_only=1
+	cleanup=1
+       KEEP_MOTION_FILES=1
+	if [ -f .preproc_cmd ]; then
+	    read cmd < .preproc_cmd
+	    cmd="${cmd/-startover/}"
+           # disable wildcard expansion so that -dicom patterns don't get expanded
+           set -f 
+           # change positional parameters to stored settings
+	    set -- $cmd
+           # re-enable wildcard expansion as usual
+	    set +f 
+	else
+	    echo "doesn't look like we've run anything yet. dont know how to -cleanup_only and -keep_motion_files"
+	    exit 1
+	fi
+      
     else
+       # don't overwrite
+       [ -r .preproc_cmd ] && mv .preproc_cmd .preproc_cmd_mv$(date +%s)
 	#write the parameter settings to file
-	echo "$@" > .preproc_cmd #for resuming failed run.
+       # for resuming failed run.
+	echo "$@" > .preproc_cmd 
     fi
 
     #echo "about to process with cmd: $@"
@@ -412,6 +459,7 @@ function parse_args {
 	elif [ $1 = -wavelet_threshold ]; then
 	    waveletThreshold="${2}"
 	    shift 2
+   # probably dont see this, -cleanup_only skips this parseing
    elif [ $1 = -keep_motion_files ] ;then
        KEEP_MOTION_FILES=1
        shift 1
@@ -492,3 +540,5 @@ function parse_args {
     [ $no_smooth -eq 0 ] && smoothing_suffix="_${smoothing_kernel}" || smoothing_suffix=
 
 }
+
+# vim: set tabstop=7:
