Updates to use template tissue masks for computing CSF and WM nuisance regressors

diff --git a/preproc_functions/nuisance_regression b/preproc_functions/nuisance_regression
--- a/preproc_functions/nuisance_regression
+++ b/preproc_functions/nuisance_regression
@@ -19,8 +19,13 @@ function warp_structmask_to_func {
 function compute_nuisance_regressors {
     declare -a nuisancecols #nuisance regressors to be concatenated
 
-    #if despiking was applied, use this file for extracting CSF, WM, GS time series. Otherwise, use the file after skull strip, motion, and slice timing
-    [ -n "${postDespike}" ] && local func_ts="${postDespike}" || local func_ts="${postSS}"
+    if [ $no_warp -eq 0 ]; then
+	#extracting time series from post-warp files to leverage tissue probability maps for templates
+	local func_ts="${postWarp}"
+    else
+	#if despiking was applied, use this file for extracting CSF, WM, GS time series. Otherwise, use the file after skull strip, motion, and slice timing
+	[ -n "${postDespike}" ] && local func_ts="${postDespike}" || local func_ts="${postSS}"
+    fi
 
     #parse comma-delimited regressors of interest into array
     OLDIFS="${IFS}"
@@ -42,84 +47,134 @@ function compute_nuisance_regressors {
 	fi
 
 	if [[ "$r" =~ ^(csf|dcsf)$ && ! -f ".csf_ts" ]]; then
-	    #fast segmentation should have been run during preprocessMprage
-	    #use pve_0 for csf
-	    #re-run FAST here if needed
-	    [ $( imtest "${mprageBet_base}_fast_seg_0" ) -eq 0 ] && rel "fast -g -o \"${mprageBet_base}_fast\" \"${mprageBet_base}\""
-
-	    warp_structmask_to_func "${mprageBet_base}_fast_pve_0" .csf_pve
-
-	    #threshold at 0.8 to ensure that only voxels likely to be csf are retained	    
-	    rel "fslmaths .csf_pve -thr 0.8 -bin .csf_pve_thr0p8"
-
-	    #erode csf mask once to reduce risk of partial volume
-	    rel "3dmask_tool -overwrite -input .csf_pve_thr0p8${ext} -dilate_result -1 -prefix .csf_pve_thr0p8_ero1${ext}"
-
-	    #cluster csf mask and only retain clusters of 5 or more contiguous voxels
-	    rel "cluster -i .csf_pve_thr0p8_ero1 -t 1.0 --osize=.csf_pve_clustsize --no_table"	    
-	    rel "fslmaths .csf_pve_clustsize -thr 5.01 -bin -mas ${postSS}_tmean_mask .csf_mask -odt char" #multiply by tight brain mask to eliminate non-brain voxels
-	    
-	    #if fewer than 20 CSF voxels (in functional space) are present, revert to a non-dilated csf mask
-	    #too few voxels may result in undue influece of a given CSF voxel on the mask average
-	    local nvox=$( 3dBrickStat -non-zero -count .csf_mask${ext} )
-
-	    if [ $nvox -lt 20 ]; then
-		rel "Warning: fewer than 20 CSF voxels were found in .csf_mask. Reverting to a non-dilated mask" c	
-		rel "cluster -i .csf_pve_thr0p8 -t 1.0 --osize=.csf_pve_clustsize_noero --no_table"
-		rel "fslmaths .csf_pve_clustsize_noero -thr 15.01 -bin -mas ${postSS}_tmean_mask .csf_mask_noero -odt char"
-
-		#obtain CSF timeseries from CSF mask in functional space
-		rel "3dmaskave -mask .csf_mask_noero${ext} -q ${func_ts}${ext} > .csf_ts" || ( echo "3dmaskave failed. Unable to extract CSF voxels. Check your mask! .wm_mask_noero${ext}" && exit 1 )
+	    #technically should probably change this to allow for use of templates for -warp_compute
+	    if [ $no_warp -eq 0 ]; then
+		#if we have a warp to standard space then use the inverse warp to transform the csf mask from the probabilistic atlas to subject space
+		if [ $templateName = MNI_3mm ]; then
+		    #thr 0.95 without erosian is best: 95 voxels
+		    rel "fslmaths \"$HOME/standard/mni_icbm152_nlin_asym_09c/mni_icbm152_csf_tal_nlin_asym_09c_3mm\" -thr 0.95 -bin .template_csf_prob"
+		elif [ $templateName = MNI_2.3mm ]; then
+		    #thr 0.98 without erosion works well here: 274 voxels
+		    rel "fslmaths \"$HOME/standard/mni_icbm152_nlin_asym_09c/mni_icbm152_csf_tal_nlin_asym_09c_2.3mm\" -thr 0.98 -bin .template_csf_prob"
+		elif [ $templateName = SPM_2mm ]; then
+		    #thr 0.6 works best here: 193 voxels
+		    rel "fslmaths \"$HOME/standard/spm8_mni/csf.nii\" -thr 0.6 -bin -eroF .template_csf_prob"	    
+		elif [ $templateName = MNI_FSL_3mm ]; then
+		    #for the FSL MNI, thr 0.5 with erosion works well visually: 87 voxels
+		    rel "fslmaths \"$HOME/standard/fsl_mni152/avg152T1_csf_3mm.nii\" -thr 0.7 -bin .template_csf_prob"	    
+		else
+		    rel "Unsupported template brain for CSF extraction: $templateName" c
+		    exit 1
+		fi
+		
+		rel "3dmaskave -mask .template_csf_prob${ext} -q ${func_ts}${ext} > .csf_ts" || ( echo "3dmaskave failed. Unable to extract CSF voxels. Check your mask! .template_csf_prob${ext}" && exit 1 )
 	    else
-		rel "3dmaskave -mask .csf_mask${ext} -q ${func_ts}${ext} > .csf_ts" || ( echo "3dmaskave failed. Unable to extract CSF voxels. Check your mask! .csf_mask${ext}" && exit 1 )
+		#use the subject's segmented anatomical scan to identify the csf voxels
+		
+		#fast segmentation should have been run during preprocessMprage
+		#use pve_0 for csf
+		#re-run FAST here if needed
+		[ $( imtest "${mprageBet_base}_fast_seg_0" ) -eq 0 ] && rel "fast -g -o \"${mprageBet_base}_fast\" \"${mprageBet_base}\""
+
+		warp_structmask_to_func "${mprageBet_base}_fast_pve_0" .csf_pve
+
+		#threshold at 0.8 to ensure that only voxels likely to be csf are retained	    
+		rel "fslmaths .csf_pve -thr 0.8 -bin .csf_pve_thr0p8"
+
+		#erode csf mask once to reduce risk of partial volume
+		rel "3dmask_tool -overwrite -input .csf_pve_thr0p8${ext} -dilate_result -1 -prefix .csf_pve_thr0p8_ero1${ext}"
+
+		#cluster csf mask and only retain clusters of 5 or more contiguous voxels
+		rel "cluster -i .csf_pve_thr0p8_ero1 -t 1.0 --osize=.csf_pve_clustsize --no_table"	    
+		rel "fslmaths .csf_pve_clustsize -thr 5.01 -bin -mas ${postSS}_tmean_mask .csf_mask -odt char" #multiply by tight brain mask to eliminate non-brain voxels
+		
+		#if fewer than 20 CSF voxels (in functional space) are present, revert to a non-dilated csf mask
+		#too few voxels may result in undue influece of a given CSF voxel on the mask average
+		local nvox=$( 3dBrickStat -non-zero -count .csf_mask${ext} )
+
+		if [ $nvox -lt 20 ]; then
+		    rel "Warning: fewer than 20 CSF voxels were found in .csf_mask. Reverting to a non-dilated mask" c	
+		    rel "cluster -i .csf_pve_thr0p8 -t 1.0 --osize=.csf_pve_clustsize_noero --no_table"
+		    rel "fslmaths .csf_pve_clustsize_noero -thr 15.01 -bin -mas ${postSS}_tmean_mask .csf_mask_noero -odt char"
+
+		    #obtain CSF timeseries from CSF mask in functional space
+		    rel "3dmaskave -mask .csf_mask_noero${ext} -q ${func_ts}${ext} > .csf_ts" || ( echo "3dmaskave failed. Unable to extract CSF voxels. Check your mask! .wm_mask_noero${ext}" && exit 1 )
+
+		else
+		    rel "3dmaskave -mask .csf_mask${ext} -q ${func_ts}${ext} > .csf_ts" || ( echo "3dmaskave failed. Unable to extract CSF voxels. Check your mask! .csf_mask${ext}" && exit 1 )
+		fi
+
+		rel "1d_tool.py -overwrite -infile .csf_ts -derivative -write .csf_ts_deriv"
+
+		#cleanup some intermediate files
+		rel "imrm .csf_pve_thr0p8 .csf_pve_thr0p8_ero1 .csf_pve_clustsize .csf_pve_clustsize_noero"
+
 	    fi
-
-	    rel "1d_tool.py -overwrite -infile .csf_ts -derivative -write .csf_ts_deriv"
-
-	    #cleanup some intermediate files
-	    rel "imrm .csf_pve_thr0p8 .csf_pve_thr0p8_ero1 .csf_pve_clustsize .csf_pve_clustsize_noero"
 	fi
 
 	if [[ "$r" =~ ^(wm|dwm)$ && ! -f ".wm_ts" ]]; then
-	    #fast segmentation should have been run during preprocessMprage
-	    #use seg_2 for wm
-	    #re-run FAST here if needed
-	    [ $( imtest "${mprageBet_base}_fast_seg_2" ) -eq 0 ] && rel "fast -g -o \"${mprageBet_base}_fast\" \"${mprageBet_base}\""
+	    if [ $no_warp -eq 0 ]; then
+		#if we have a warp to standard space then use the inverse warp to transform the csf mask from the probabilistic atlas to subject space
+		if [ $templateName = MNI_3mm ]; then
+		    #0.9 with erosion gives nice mask: 793 voxels
+		    rel "fslmaths \"$HOME/standard/mni_icbm152_nlin_asym_09c/mni_icbm152_wm_tal_nlin_asym_09c_3mm\" -thr 0.9 -bin -eroF .template_wm_prob"
+		elif [ $templateName = MNI_2.3mm ]; then
+		    #0.95 with erosion: 2681 voxels
+		    rel "fslmaths \"$HOME/standard/mni_icbm152_nlin_asym_09c/mni_icbm152_wm_tal_nlin_asym_09c_2.3mm\" -thr 0.95 -bin -eroF .template_wm_prob"
+		elif [ $templateName = SPM_2mm ]; then
+		    #0.85 with erosion: 2981 voxels
+		    rel "fslmaths \"$HOME/standard/spm8_mni/white.nii\" -thr 0.85 -bin -eroF .template_wm_prob"
+		elif [ $templateName = MNI_FSL_3mm ]; then
+		    #0.8 with erosion: 659 voxels
+		    rel "fslmaths \"$HOME/standard/fsl_mni152/avg152T1_white_3mm.nii\" -thr 0.8 -bin -eroF .template_wm_prob"	    
+		else
+		    rel "Unsupported template brain for CSF extraction: $templateName" c
+		    exit 1
+		fi
 
-	    warp_structmask_to_func "${mprageBet_base}_fast_pve_2" .wm_pve
-
-	    #threshold at 0.8 to ensure that only voxels likely to be wm are retained	    
-	    rel "fslmaths .wm_pve -thr 0.8 -bin .wm_pve_thr0p8"
-
-	    #erode wm mask twice to reduce risk of partial WM voxels
-	    #more contiguous wm voxels than csf voxels -- hence 2x dilation works well in general as a start to retain deep cerebral white matter
-	    rel "3dmask_tool -overwrite -input .wm_pve_thr0p8${ext} -dilate_result -2 -prefix .wm_pve_thr0p8_ero2${ext}"
-
-	    #cluster wm mask and only retain clusters of 15 or more contiguous voxels
-	    rel "cluster -i .wm_pve_thr0p8_ero2 -t 1.0 --osize=.wm_pve_clustsize --no_table"
-	    rel "fslmaths .wm_pve_clustsize -thr 15.01 -bin -mas ${postSS}_tmean_mask .wm_mask -odt char"
-	    
-	    #check that at least 100 voxels are present in mask to get a reasonable sampling distribution of WM timeseries
-	    local nvox=$( 3dBrickStat -non-zero -count .wm_mask${ext} )
-
-	    if [ $nvox -lt 50 ]; then
-		#go back to a 1x erosion, but up voxel clusters to 50 minimum
-		rel "Warning: fewer than 50 WM voxels were found in .wm_mask. Reverting to a 1x eroded WM mask" c
-		rel "3dmask_tool -overwrite -input .wm_pve_thr0p8${ext} -dilate_result -1 -prefix .wm_pve_thr0p8_ero1${ext}"
-		
-		rel "cluster -i .wm_pve_thr0p8_ero1 -t 1.0 --osize=.wm_pve_clustsize_ero1 --no_table"
-		rel "fslmaths .wm_pve_clustsize_ero1 -thr 50.01 -bin -mas ${postSS}_tmean_mask .wm_mask_ero1 -odt char"
-
-		#obtain average WM timeseries from WM mask in functional space
-		rel "3dmaskave -mask .wm_mask_ero1${ext} -q ${func_ts}${ext} > .wm_ts" || ( echo "3dmaskave failed. Unable to extract WM voxels. Check your mask! .wm_mask_ero1${ext}" && exit 1 )
+		rel "3dmaskave -mask .template_wm_prob${ext} -q ${func_ts}${ext} > .wm_ts" || ( echo "3dmaskave failed. Unable to extract WM voxels. Check your mask! .template_wm_prob${ext}" && exit 1 )
 	    else
-		rel "3dmaskave -mask .wm_mask${ext} -q ${func_ts}${ext} > .wm_ts" || ( echo "3dmaskave failed. Unable to extract WM voxels. Check your mask! .wm_mask${ext}" && exit 1 )
-	    fi    
 
-	    rel "1d_tool.py -overwrite -infile .wm_ts -derivative -write .wm_ts_deriv"
+		#fast segmentation should have been run during preprocessMprage
+		#use seg_2 for wm
+		#re-run FAST here if needed
+		[ $( imtest "${mprageBet_base}_fast_seg_2" ) -eq 0 ] && rel "fast -g -o \"${mprageBet_base}_fast\" \"${mprageBet_base}\""
 
-	    #cleanup some intermediate files
-	    rel "imrm .wm_pve_thr0p8 .wm_pve_thr0p8_ero2 .wm_pve_thr0p8_ero1 .wm_pve_clustsize .wm_pve_clustsize_noero_ero1"
+		warp_structmask_to_func "${mprageBet_base}_fast_pve_2" .wm_pve
+
+		#threshold at 0.8 to ensure that only voxels likely to be wm are retained	    
+		rel "fslmaths .wm_pve -thr 0.8 -bin .wm_pve_thr0p8"
+
+		#erode wm mask twice to reduce risk of partial WM voxels
+		#more contiguous wm voxels than csf voxels -- hence 2x dilation works well in general as a start to retain deep cerebral white matter
+		rel "3dmask_tool -overwrite -input .wm_pve_thr0p8${ext} -dilate_result -2 -prefix .wm_pve_thr0p8_ero2${ext}"
+
+		#cluster wm mask and only retain clusters of 15 or more contiguous voxels
+		rel "cluster -i .wm_pve_thr0p8_ero2 -t 1.0 --osize=.wm_pve_clustsize --no_table"
+		rel "fslmaths .wm_pve_clustsize -thr 15.01 -bin -mas ${postSS}_tmean_mask .wm_mask -odt char"
+		
+		#check that at least 50 voxels are present in mask to get a reasonable sampling distribution of WM timeseries
+		local nvox=$( 3dBrickStat -non-zero -count .wm_mask${ext} )
+
+		if [ $nvox -lt 50 ]; then
+		    #go back to a 1x erosion, but up voxel clusters to 50 minimum
+		    rel "Warning: fewer than 50 WM voxels were found in .wm_mask. Reverting to a 1x eroded WM mask" c
+		    rel "3dmask_tool -overwrite -input .wm_pve_thr0p8${ext} -dilate_result -1 -prefix .wm_pve_thr0p8_ero1${ext}"
+		    
+		    rel "cluster -i .wm_pve_thr0p8_ero1 -t 1.0 --osize=.wm_pve_clustsize_ero1 --no_table"
+		    rel "fslmaths .wm_pve_clustsize_ero1 -thr 50.01 -bin -mas ${postSS}_tmean_mask .wm_mask_ero1 -odt char"
+
+		    #obtain average WM timeseries from WM mask in functional space
+		    rel "3dmaskave -mask .wm_mask_ero1${ext} -q ${func_ts}${ext} > .wm_ts" || ( echo "3dmaskave failed. Unable to extract WM voxels. Check your mask! .wm_mask_ero1${ext}" && exit 1 )
+		else
+		    rel "3dmaskave -mask .wm_mask${ext} -q ${func_ts}${ext} > .wm_ts" || ( echo "3dmaskave failed. Unable to extract WM voxels. Check your mask! .wm_mask${ext}" && exit 1 )
+		fi    
+
+		rel "1d_tool.py -overwrite -infile .wm_ts -derivative -write .wm_ts_deriv"
+
+		#cleanup some intermediate files
+		rel "imrm .wm_pve_thr0p8 .wm_pve_thr0p8_ero2 .wm_pve_thr0p8_ero1 .wm_pve_clustsize .wm_pve_clustsize_noero_ero1"
+	    fi
 	fi
 
 	#global signal
