add 3dREMLfit to regression options and test

diff --git a/preproc_functions/nuisance_regression b/preproc_functions/nuisance_regression
--- a/preproc_functions/nuisance_regression
+++ b/preproc_functions/nuisance_regression
@@ -25,9 +25,77 @@ motionderiv() {
   return 0
 }
 
-COMPUTE_NUISANCE_REGRESSORS_GLOBALS=(nuisance_file nuisance_regressors no_warp postWarp postDespike postSS templateName mprageBet_base ext)
+COMPUTE_NUISANCE_REGRESSORS_GLOBALS=(nuisance_file nuisance_regressors no_warp postWarp postDespike postSS templateName mprageBet_base ext tr prefix bpLow bpHigh)
+
+# give 
+# - a nifti get basis functions to remove autocorrelation
+# - output
+# - optional: mask
+# write file to $out with 3dREMLfit to bandpass, remove regressors, remove autocorralation
+# USAGE:
+# remove_autocorr_and_br dnswdktm_restepi_5.nii.gz Rdnswdktm_restepi_5.nii.gz wktm_restepi_98_2_mask_dil1x_templateTrim.nii.gz
+# GOBAL $tr, $nuisance_file, $bpLow, $bpHigh
+# there is lots of boilerplate checks. at the heart this runs 2 commands
+# 1) 1dBport to generate bandpass sine/cosine and basis function (to remove autocorr)
+# 2) 3dREMLfit to remove these
+function remove_autocorr_and_br(){
+  img=$1
+  out=$2
+  mask=$3
+
+  [ -r .remove_autocorr_complete ] && return 0
+
+  [ ! -r $img ]  && echo "$FUNCNAME missing image ($img)" >&2 && return 1
+  nvol=$(3dinfo -nt $img)
+  [ -z "$nvol" -o $nvol -lt 1 ] && echo "$FUNC_NAME: bad number of timesteps ($nvol) in $img" >&2 && return 1
+
+
+
+  bandoption=""
+  if [ "$bandpass_filter" -eq 1 ]; then
+     if [ -z "$bpLow" -o -z "$bpHigh" ]; then
+       rel "ERROR! $FUNC_NAME has no bandpass low or high parameters, but we said bandpass!" c
+       return 1
+     fi
+     bandoption="-band $bpLow $bpHigh"
+  else
+     #rel "WARNING! AFNI gurus say you probably WANT bandpassing. You are NOT bandpassing (by setting no low pass and highpass above nyquist" c
+     #bandoption="-band 0 100000"
+       rel "ERROR! I think you need to bandpass to remove autocorrelation. Sorry." c
+       return 1
+
+  fi
+
+  rel "1dBport -nodata $nvol $tr $bandoption -quad -invert > .basis.1d"
+  # same as '-nodata $nvol $tr' is same as '-input $img'
+
+  reml_in_file=$nuisance_file.rmautcorr
+
+  if [ "$nuisance_regression" -eq 1 ]; then
+   rel "paste $nuisance_file .basis.1d > $reml_in_file"
+  else
+   rel "cp .basis.1d $reml_in_file"
+  fi
+  # could also try below, but get different results!
+  # regoption="-stimbase $nuisance_file"
+
+  # are we using a mask?
+  maskoption=""
+  [ -n "$mask" ] && imtest "$mask" && maskoption="-mask $mask"
+
+  rel "3dREMLfit -input $img $maskoption -matim $reml_in_file -Rerrts $out"
+  rel "date > .remove_autocorr_complete"
+  return 0
+}
 
 function compute_nuisance_regressors {
+
+    # 20170421WF: skipping might be a problem if we change what regressors we want
+    if [ -r .nuisance_compute_complete ]; then
+       rel "already computed nuisance regression" c
+       return 0
+    fi
+
     declare -a nuisancecols #nuisance regressors to be concatenated
 
     if [ $no_warp -eq 0 ]; then
@@ -328,20 +396,38 @@ function compute_nuisance_regressors {
     # 20151218 WF -- "star" instead of "at" so single shell-world (one argument) sent to rel
     rel "1dcat ${nuisancecols[*]} > ${nuisance_file}"
     
+    # TODO: do multiple passes to build nuisancols so we can check that would should be redoing?
+    rel "echo '${nuisancecols[*]}' > .regressors_in_use"
+
+    rel "date > .nuisance_compute_complete"
+
     return 0
 }
 
 function nuisance_regression {
     #handle nuisance regression and/or bandpass filtering
-    [[ "$nuisance_compute" -eq 0 && "$nuisance_regression" -eq 0 && "$bandpass_filter" -eq 0 ]] && return 0 #no nuisance or bandpass, exit
+    if [[ \
+         "$nuisance_compute"    -eq 0 &&  \
+         "$nuisance_regression" -eq 0 &&  \
+         "$bandpass_filter"     -eq 0 &&  \
+         "$autocorr_with_basis" -eq 0     \
+    ]]; then
+      rel "(Not trying to deal with nuisance regressors, bandpassing, or autocorrelation)" c
+      return 0 #no nuisance, bandpass, or basis correct. exit
+    fi
 
     preNRBP="${prefix}${funcFile}${smoothing_suffix}${ext}"
     
     local todo=
-    if [[ "$nuisance_regression" -eq 1 && "$bandpass_filter" -eq 1 ]]; then todo="br" #bandpass and regression
-    elif [ "$nuisance_regression" -eq 1 ]; then todo="r" #regression only
-    elif [ "$bandpass_filter" -eq 1 ]; then todo="b" #bandpass alone
-    fi
+    [ $autocorr_with_basis -eq 1 ] && todo="${todo}a"
+    [ $bandpass_filter     -eq 1 ] && todo="${todo}b"
+    [ $nuisance_regression -eq 1 ] && todo="${todo}r"
+
+    # todo is 
+    #  only: a b r 
+    #  combined: ab abr br
+    #  'a' alone is not allowed, will throw error -- checked by parseargs or preprocessFunctional
+    
 
     prefix="${todo}${prefix}"
     postNRBP="${prefix}${funcFile}${smoothing_suffix}${ext}"
@@ -350,6 +436,9 @@ function nuisance_regression {
     [[ -f .nuisance_regression_complete && $todo=r ]] && return 0
     [[ -f .bandpass_filter_complete && $todo=b ]] && return 0
     [[ -f .nuisance_regression_complete && -f .bandpass_filter_complete && $todo=br ]] && return 0
+
+    # 20170420WF: if we completed todo=a* we might still hit compute_nuisance_regressors
+    #  compute_nuisance_regressors now checks if it's been run before
 
     if [[ ! -f "${nuisance_file}" && ( $nuisance_regression == 1 || $nuisance_compute == 1 ) ]]; then
 	compute_nuisance_regressors
@@ -361,12 +450,8 @@ function nuisance_regression {
 		-prefix \"$postNRBP\" $bpLow $bpHigh"
 
 	rel "date > .bandpass_filter_complete"
-    elif [ "$todo" = "br" ]; then
-        rel "3dBandpass -overwrite -input \"$preNRBP\" -mask \"${subjMask}${ext}\" -dt $tr \
-		-prefix \"$postNRBP\" -ort ${nuisance_file} $bpLow $bpHigh"
 
-	rel "date > .bandpass_filter_complete"
-	rel "date > .nuisance_regression_complete"
+    # regress only
     elif [ "$todo" = "r" ]; then
         rel "3dDetrend -overwrite -verb -polort 2 -vector ${nuisance_file} \
 		-prefix \"$postNRBP\" \"$preNRBP\""
@@ -374,6 +459,26 @@ function nuisance_regression {
 	#need to mask detrend by brain mask as with 3dBandpass
 	rel "fslmaths \"$postNRBP\" -mas \"$subjMask\" \"$postNRBP\""
 	rel "date > .nuisance_regression_complete"
+
+    # bandpass and regress
+    elif [ "$todo" = "br" ]; then
+        rel "3dBandpass -overwrite -input \"$preNRBP\" -mask \"${subjMask}${ext}\" -dt $tr \
+		-prefix \"$postNRBP\" -ort ${nuisance_file} $bpLow $bpHigh"
+
+	rel "date > .bandpass_filter_complete"
+	rel "date > .nuisance_regression_complete"
+
+    # 20170420WF -- added for MJ w/MH suggestsions
+    # remove autocorliation + bandpass and regress
+    elif [[ "$todo" =~ ^a ]]; then
+       # may or may not have computed regressors
+       # will use them if .nuisance_regressors exists
+       # will test for .remove_autocorr_complete
+       remove_autocorr_and_br $preNRBP $postNRBP ${subjMask}${ext}
+
+    # we were only computing things
+    else
+       rel "(Regressors computed but no bandpass or nuisance regression)" c
     fi
     
     #explicit return code needed to avoid implicit status of prior command
diff --git a/preproc_functions/parse_args b/preproc_functions/parse_args
--- a/preproc_functions/parse_args
+++ b/preproc_functions/parse_args
@@ -1,9 +1,14 @@
 #!/bin/bash
 
-# rm_completefiles -- in helper_functions 
-function parse_args {
-    #parse input arguments, initialize default parameter settings
-    #when called from preprocessFunctional, must pass "$@", which is all input parameters to script
+## where to look for finding the standard space template directory
+# expect files like:
+#   talairach_fsl_mni152/TalFSL_MNI152_T1_3mm_brain
+#   fsl_mni152/MNI152_T1_3mm_brain
+#   mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain_3mm
+#   mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain_2.3mm
+#   spm8_mni/T1_brain
+#   mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain_2mm
+function find_standard_template_dir(){
 
     # where can we find standard space brain templates
     # prefer ACI installation
@@ -13,7 +18,7 @@ function parse_args {
        $HOME/standard \
      )
 
-    stddir=
+    local stddir=
     for stddir in ${standard_spaces[@]}; do
        [ -d "$stddir" ] && break
     done
@@ -23,6 +28,17 @@ function parse_args {
       return 1
     fi
 
+    echo $stddir
+    return 0
+
+}
+
+## parse input arguments, initialize default parameter settings
+## when called from preprocessFunctional, must pass "$@", which is all input parameters to script
+# rm_completefiles -- in helper_functions 
+function parse_args {
+    stddir=$(find_standard_template_dir)
+    [ -z $stddir ] && return 1
     
     #initialize defaults
     funcFile=
@@ -57,6 +73,7 @@ function parse_args {
     no_st=0
     no_smooth=0
     no_warp=0
+    autocorr_with_basis=0 # -rmautocorr, 20170420WF -- added in nuisance_regression, 3dREMLfit basis 
     nuisance_regression=0
     nuisance_compute=0
     nuisance_file=.nuisance_regressors
@@ -336,6 +353,9 @@ function parse_args {
 	elif [ $1 = -ref_vol ] ; then
             ref_vol="${2}"
             shift 2
+       elif [ $1 = -rmautocorr ]; then
+           autocorr_with_basis=1
+           shift
 	elif [ $1 = -rescaling_method ]; then
 	    if [[ $2 = "10000_globalmedian" || $2 = "100_voxelmean" ]]; then
 		rescalingMethod="${2}"
@@ -482,6 +502,11 @@ function parse_args {
 
     if [[ $sliceMotion4D -eq 1 && $mc_first -eq 1 ]]; then
 	echo "Cannot request -mc_first with -4d_slice_motion"
+	exit 1
+    fi
+
+    if [[ $autocorr_with_basis -eq 1 && $bandpass_filter -eq 0 ]]; then
+	echo "Cannot request -rmautocorr without -bandpass_filter "
 	exit 1
     fi
 
