check for optional depend octave||matlab

diff --git a/preproc_functions/parse_args b/preproc_functions/parse_args
--- a/preproc_functions/parse_args
+++ b/preproc_functions/parse_args
@@ -129,6 +129,9 @@ function parse_args {
        if [ $1 = -check_dependencies ]; then 
           set +e
           trap - ERR
+          if ! (command -v matlab >/dev/null || command -v octave >/dev/null); then
+             echo "Optional: matlab or octave is required for wavelet despiking" >&2
+          fi
           check_dep_list 3dcalc fslmaths python antsRegistrationSyN.sh c3d_affine_tool python:nipy python:nibabel perl:App::AFNI::SiemensPhysio python:future
           exit $?
 	elif [ $1 = -cleanup_only ]; then
