🐛 func template and mni template dont have to have same res
updated templte_func check (with TODO) and smoothing func
smoothing uses func template instead of t1 template

diff --git a/preproc_functions/parse_args b/preproc_functions/parse_args
--- a/preproc_functions/parse_args
+++ b/preproc_functions/parse_args
@@ -699,7 +699,8 @@ function parse_args {
     #Hence, because FSL expects our smoothing specification to be a sigma,
     #we divide the FWHM value provided by $smoothing_kernel by 2.355 (approximately 8*log(2).
     [[ "$smoothing_kernel" == "default" ]] &&
-	smoothing_kernel=$(get_default_smoothing "$mprageBet")
+	smoothing_kernel=$(get_default_smoothing "$templateName") &&
+        rel "smoothing change from 'default' to '$smoothing_kernal' (for '$templateName' )" c >&2
     [ -z "$smoothing_kernel" -a $no_smooth -eq 0 ] &&
 	echo "cannot continue without smoothing kernel" && exit 1
 
@@ -913,18 +914,29 @@ load_func_bids(){
 }
 
 get_default_smoothing() {
+  # input either matches [0-9.]+mm$ (functional tempate) or a nifti file
   # smooth size default based on desired resolution.
   # will be overwritten if '-- -smoothing_kernel x' specified
   # find_mprage_warp is from func_template. must be loaded
-  local bet="$1"
-  local template=$(find_mprage_warp "$bet" "template_brain.nii*")
-  [ -z "$template" ] && echo "cannot find template from mprage bet  '$mprageBet'" >&2 && return 1
-  local res=$(3dinfo -adi $template) # all templates are symetric (2x2x2)
+  local ref=$1
+  local res=0
+  if [[ $ref =~ _([0-9.]+)mm$ ]]; then
+      res=${BASH_REMATCH[1]}
+  elif [ -r "$ref" ]; then
+      res=$(3dinfo -adi "$ref") # all templates are symetric (2x2x2)
+  else
+      echo "ERROR: cannot determine what smoothing kernel should be with ref '$ref'" >&2
+      return 1
+  fi
+
+  local smooth_at=
   case $res in
-      2.0*) echo 4;;
-      2.5*) echo 5;;
-      3.0*) echo 5;;
-      *) echo "$FUNCNAME: smoothing size for res '$res' of '$template' not specified. manually specify like '-smoothing_kernel X' (in mm)" >&2; return 1;;
+      2.5*) smooth_at=5;;
+      2.3*) smooth_at=5;;
+      2*) smooth_at=4;;
+      3*) smooth_at=5;;
+      *) echo "$FUNCNAME: smoothing size for res '$res' of '$ref' not specified. manually specify like '-smoothing_kernel X' (in mm)" >&2; return 1;;
   esac
+  echo "$smooth_at"
 }
 # vim: set tabstop=7:
