Fix case for auto-corr removal check; don't enforce bandpass+rmautocorr in parse_args

diff --git a/preproc_functions/parse_args b/preproc_functions/parse_args
--- a/preproc_functions/parse_args
+++ b/preproc_functions/parse_args
@@ -527,10 +527,10 @@ function parse_args {
 	exit 1
     fi
 
-    if [[ $autocorr_with_basis -eq 1 && $bandpass_filter -eq 0 ]]; then
-	echo "Cannot request -rmautocorr without -bandpass_filter "
-	exit 1
-    fi
+#    if [[ $autocorr_with_basis -eq 1 && $bandpass_filter -eq 0 ]]; then
+#	echo "Cannot request -rmautocorr without -bandpass_filter "
+#	exit 1
+#    fi
 
     #whether to use a fieldmap, either GRE or TOPUP
     use_fm=0
