fast_wmseg explicit return, rel explicit exit status; quote warpdir in reg stuct2func

diff --git a/preproc_functions/register_func2struct b/preproc_functions/register_func2struct
--- a/preproc_functions/register_func2struct
+++ b/preproc_functions/register_func2struct
@@ -26,17 +26,22 @@ function register_func2struct {
     if [[ -n "${fm_phase}" || ( -n "${se_phasepos}" && $topup_direct -eq 0 ) || -n "$DISTORTION_DIR" ]]; then
 
 	inweight="-inweight $(pwd)/unwarp/EF_UD_fmap_sigloss"
+        [ -z "$unwarpdir" -a ! -n "$fm_cfg" ] && rel "$FUNCNAME doesn't know about fieldmaping, something is strange" c && find_and_source_fmconfig "$fm_cfg"
+        # if that didn't work we have problems
+        if [ -z "$unwarpdir" ]; then
+          warn "isfm (fm_phase '$fm_phase', se_phasepos '$se_phasepos', or DISTORTION_DIR '$DISTORTION_DIR') but unrecoginzed fm_cfg '$fm_cfg'" 
+          return 1
+        fi
 	#echo spacing and phase encode direction should be defined when $fm_cfg is sourced by prepareFieldmap (upstream)
 	#need to convert pedir to numeric codes x=1, y=2, z=3
-	case $unwarpdir in
+	case "$unwarpdir" in
 	    x)     bbr_pedir=1  ;;
 	    -x|x-) bbr_pedir=-1 ;;
 	    y)     bbr_pedir=2  ;;
 	    -y|y-) bbr_pedir=-2 ;; 
 	    z)     bbr_pedir=3  ;;
 	    -z|z-) bbr_pedir=-3 ;;
-	    *)     echo "$FUNCNAME Unable to determine unwarping direction from '$unwarpdir'"
-		exit 1 ;;
+	    *)     warn "$FUNCNAME Unable to determine unwarping direction from '$unwarpdir'"; exit 1 ;;
 	esac
 
 	bbrfmap="-fieldmap $(pwd)/unwarp/fmapForBBR -pedir $bbr_pedir -echospacing $dwelltime"
